# todo:
# press start
# pull trigger to shoot ball
# replay at
# top marksman
# skeleton lighting
# williams logo
# T2
# special thanks

Sequence:
    - LastScores:
        Font: attract_font
        FontStyle:
            interior_color: [130,230,130]
            line_width: 1
            line_color: [60,60,60]
        Background: dark_chrome
        lampshow: attract_show_2
        duration: 2.0
    - Combo:
        Text:
            - "MOcean"
            - ""
            - "Presents"
        Font: attract_font
        FontStyle:
            interior_color: [130,230,130]
            line_width: 1
            line_color: [60,60,60]
        Animation: dark_chrome
        lampshow: attract_show_2
        sound: sling
        duration: 2.0
    - Combo:
        Text:
            - "Terminator"
            - ""
            - "2.0"
        Font: attract_font
        FontStyle:
            interior_color: [130,230,130]
            line_width: 1
            line_color: [60,60,60]
        lampshow: attract_show_2
        duration: 2.0
    - panning_layer:
        width: 500
        height: 500
        origin_x: 0
        origin_y: -130
        scroll_x: 0
        scroll_y: 2
        frames_per_movement: 2
        bounce: False
        contents:
            group_layer:
                width: 500
                height: 500
                contents:
                    - animation_layer:
                        name: dark_chrome
                    - markup_layer:
                        width: 450
                        Bold:
                            Font: attract_font
                            FontStyle: blueish
                        Normal:
                            Font: attract_font
                            FontStyle: blueish
                        Message:
                            - "#Special Thanks to:#"
                            - "#Gerry Stellenberg#"
                            - "#Adam Preble#"
                            - "#Josh (Rosh) Kugler#"
                            - "#Scott Danesi#"
                            - "Matt Bonema#"
        duration: 4.0
    - Animation:
        Name: t800-war
        sound: target_bank
    - HighScores:
        Font: attract_font
        Background: dark_chrome
        Order:
            - player
            - category
            - score
        duration: 4.0 # increase duration since it is now the length of all high score frames, together!